# HW 7 - Libraries + Modules
ULAB - Physics and Astronomy Division \
Due **Wednesday, November 6th, 2024 at 11:59pm** on Gradescope

--------------------------------------------------------------

## Module vs. Package vs. Library
### Module
A **module** is a single file containing Python code (typically ending in a `.py` extension) that contains functions and variables. 
- They can be imported into other Python files or notebooks
- You use modules to organize code into smaller, reuseable parts
- Ex: `even_sum.py` that we created during lecture.

*You will create your OWN module for this homework and use that we made during class.*

### Package
A **package** is a group of modules, organized like a directory. 
- A package requires a special `__init__.py` file to tell Python that the ENTIRE directory is something you would like to import.
- Packages can contain sub-pacakges
- Ex: `BAGLE_Microlensing` is an example of a package (if you are in Dex's group, this should be familar to you). Or you could think of `paarti` if you are in Brianna's group.

*You will NOT be working with a package for this homework.*

### Library
A **library** is a much broader term that also refers to a collection of modules (like a package) but a library can also contain mulitple packages. 
- Libraries serve a much wider range of functionality for
- Programmers use packages to have ready-to-go tools that can be used for data manipulation, web development, machine learning or simulations.
- Ex: `numpy` is a very common library. Later in this course we will also be working some of the following libraries `matplotlib`, `scipy`, and `astropy`, `pandas`, etc

*You WILL be working with the extensive numpy library for this homework!*

--------------------------------------------------------------

# 1 NumPy
**NumPy** (aka Numerical Python) is a library that was designed for caring out computations in Python. 

We did not have a ton of time to work through examples during class, so I will ask that you check out this website for more information: https://numpy.org/doc/ 

Before we can work through any problems, you need to call the following in your notebook:

In [68]:
import numpy as np

## 1.1 Lists vs. Arrays
*When I first started working with NumPy I didn't understand what was so special about arrays. This homework problem should help illustrate the difference. Make sure to follow each step and follow good coding practices.*

1) Make a list called `my_list` and make an array called `my_arr` with the same values. There is an example below, but don't copy mine! Ex:
```
my_list = [11, 12, 13, 14, 15]
my_arr = np.array([11, 12, 13, 14, 15])
```
*Notice that to use the `numpy` package we had to call its short cut `np` and then call upon its funciton `.array()`. This is similar to working with a built-in python function like `.append()`.*

In [70]:
my_list = [1,2,29,7,10]
my_arr = np.array([1,2,29,7,10])

2) Multiply `my_list` by 4 and multiply `my_arr` by 4. Print the results. Describe what happens in a comment.

In [72]:
print(my_list*4) # list is appended to itself 4 times
print(my_arr*4) # items in list are multiplied by four individually


[1, 2, 29, 7, 10, 1, 2, 29, 7, 10, 1, 2, 29, 7, 10, 1, 2, 29, 7, 10]
[  4   8 116  28  40]


3) Add `my_list` with `my_list`. Add `my_arr` with `my_arr`. Add `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [74]:
print(my_list + my_list) # list is appended to itself
print(my_arr + my_arr) # each item in array is added to itself
print(my_list + my_arr) # each item in list is added to each item in array

[1, 2, 29, 7, 10, 1, 2, 29, 7, 10]
[ 2  4 58 14 20]
[ 2  4 58 14 20]


4) Subtract `my_list` with `my_list`. Subtract `my_arr` with `my_arr`. Subtract `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [76]:
# print(my_list - my_list) 
# subtracting lists gives an error, "unsupported operand types(s) for -: 'list' and 'list'

print(my_arr - my_arr) # each value in my array is subrated from itself
print(my_list - my_arr) # each value in my array is subracted by each corresponding element in my list

[0 0 0 0 0]
[0 0 0 0 0]


5) Multiply `my_list` with `my_list`. Multply `my_arr` with `my_arr`. Multiply `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [78]:
# print(my_list * my_list)
# return a TypeError: "can't multiply sequence by non-int of type 'list'

print(my_arr * my_arr) # each value in my array is multiplied by itself
print(my_list * my_arr) # each value in my array is multiplied by each corresponding element in my list

[  1   4 841  49 100]
[  1   4 841  49 100]


7) Divide `my_list` with `my_list`. Divide `my_arr` with `my_arr`. Divide `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [80]:
# print(my_list/my_list)
# Returns TypeError: "unsupported operand type(s) for /: 'list' and 'list'

print(my_arr/my_arr) # each value in my array is divided by istelf 
print(my_list/my_arr) # each value in my list is divided by each value in my array

[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]


8) After working through this problem, in at least two sentences, describe the difference between a list and an array.

In [82]:
# A list is a sequence of various elements of different types.

# An array is a sequence of elements of the same data type.

# Because of this difference, arrays are supported by more operant types than lists. Can be used for math. 


## 1.2 Nested List and Multi-Dimensional Arrays
A **nested list** is when you have a list as an element for a list. Example:
```
nested_list = [[1, 2, 3], [4, 5, 6]]
```

A **multi-dimensional array** is essentially a nested list, but it contains the properties of a matrix. Example:
```
multi_d_array = np.array([[1, 2, 3], [4, 5, 6]])
```

Go to this website for more information on NumPy: https://www.w3schools.com/python/numpy/default.asp

Write a **function** that takes in a two-dimensional array. Example:

```
arr3 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
```

and then returns the second value in each row. Example:

```
[4, 10, 16]
```

In [84]:
def j_value_2D(arr):
    #takes the "j" (second) value of each row in a 2 dimensional array, inputs a 2 dimensional array
    j_list = []
    for i in range(len(arr)):
        j_list.append(arr[i][1])
    return j_list
    
arr = np.array([[1,2,3],[4,5,6]])
arr1 = np.array([[1,2,3,4],[2,3,1,4],[9,6,75,4],[4,21,3,5],[0.3,0,7,4]])

print(j_value_2D(arr))
print(j_value_2D(arr1))

[2, 5]
[2.0, 3.0, 6.0, 21.0, 0.0]


In 2-3 sentences, describe what section of the website helped you write your function. 

In [86]:
# I did not use the website to help me write the function I used. But to visualize what was happening
# I went to user guide, then in "getting started" I clicked on "Numpy: the absolute basics for beginners".
# Reading the "Creating Matrices" chapter in this section was helpful.


How would you take a nested list and return the second value in each row? Explain in 2-3 sentences and show an example.

In [88]:
# I would take for loop to acces each element in my nested list, then take the second values and 
# append it to another list which I will return in the function

list = [[1,2,3],[4,5,6],[7,8,9]]

def second_2D_value(list_2D):
    # This function returns the second value of each row of a 2 dimensional list
    second = []
    for element in list_2D:
        second.append(element[1])
    return second
    
second_value = second_2D_value(list)

print(second_value)


[2, 5, 8]


## 1.3 Up to You!
With the website I just gave you: https://www.w3schools.com/python/numpy/default.asp

I recommend working through the examples they provide (you don't have to do all of them, but a few would be good). It will help you build an intuition for numpy. It won't take very long, there are only a couple of examples per section.

Write you own **function** that follows the theme of one of the sections (i.e. array reshaping, array filter, random intro, etc). For example, if you are curious about the section "**NumPy Creating Arrays**" you could write a function that creates a multi-dimensional array.

```

>>> def make_multi_dimensional_array(one_d_array, dimensions):
...     # Creates a multi-dimensional array
...     # Your code here
...     return # Your code here

>>> my_one_d_array = [2, 4, 6, 8]
>>> my_dimension = 10
>>> ten_d_array = make_multi_dimensional_array(my_one_d_array, my_dimension)
>>> print(ten_d_array)
[[[[[[[[[[2 4 6 8]]]]]]]]]]

```

Your function should be more detailed than the example I gave you. Include at least one of the following: 
- a conditional statement
- an assignment operator
- a loop (`for` or `while`)
- `if`, `elif`, `else`, statement

In [90]:
import numpy as np

def multidimension(one_d_array,dim):
    #This function creates a multidimensional array from a one dimensional array
    for i in range(dim-1):
        array2 = np.array([one_d_array])
        one_d_array = array2
    return array2

old_array = np.array((1,2,3,4,5))
four_d_array = multidimension(old_array,4)

print(four_d_array)

[[[[1 2 3 4 5]]]]


In the section you took inspiration from, show all of the examples below. Follow good coding practices and give at least two test cases for each example. Don't forget comments! \
\
*For my example, I took inspiration from **NumPy Creating Arrays** so I would show following examples with DIFFERENT test cases: Create a NumPy ndarray Object, Dimensions in Arrays ,0-D Arrays, 1-D Arrays, 2-D Arrays, 3-D Arrays, Check Number of Dimensions, Higher Dimensional Arrays.*

In [92]:
# In NumPy, Creating Arrays, I took inspiration from this example in "Higher Dimensional Arrays":
import numpy as np
arr = np.array([1,2,3,4,5], ndmin = 5)
print(arr)
print('number of dimensions :', arr.ndim)
# After looking at the output, I figured that I had to create a function that fullfils
# np.array([1,2,3,4,5],ndmin = 5)
# So, I was inspired to start my function with just one element to simplify the problem, and think
# How the output can be recreated with a for loop.

[[[[[1 2 3 4 5]]]]]
number of dimensions : 5


In 2-3 sentences, describe how your function took inspiration from a section.\
\
*For my example, `make_multi_dimensional_array`, I would talk about the **NumPy Creating Arrays** section and how I took inspiration from the example **Higher Dimensional Arrays**.*

In [94]:
# I also took inspiration from an example in "3D Arrays":
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
# After looking at the output, I was able to decipher what separated an element from an array in
# multidimensional arrays. The struggle to do so made me think about how one would make the same 
# function but taking a two dimensional array as an input. And connecting the similarities.

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# 2 Brianna's Module
During lecture we created and worked with a module called `even_sum.py`. Import that module here. 

In [96]:
import even_sum as es

Now that you have imported the module. Call the module and the first function with your own list of numbers. 

In [98]:
list = [1,2,3,4,5]
es.sum_even_numbers(list)

6

I have provided you a separate module called `example.py`. Import that module here.

In [100]:
import example as ex

With the following variables, use my module to show which of the rocket's escape!

In [102]:
rocket_velocities = np.array([
    [1000, 5000, 8000, 12000],  # Rocket 1's velocity at different times
    [2000, 6000, 9000, 10000],  # Rocket 2
    [3000, 3100, 3200, 3300]    # Rocket 3
])

mass_of_planet = 5.972e24 # kilograms
radius_of_planet = 6.371e6 # meters

In [104]:
esc_velocity = ex.escape_velocity(mass_of_planet,radius_of_planet)
orb_velocity = ex.orbital_velocity(mass_of_planet,radius_of_planet)
statuses = ex.rocket_launch(rocket_velocities,mass_of_planet,radius_of_planet)
print(statuses)

['Rocket left the planet!', 'Rocket is orbiting around the planet.', 'Rocket crashes back into the planet!']


In 2-3 sentences describe how this code follows "good coding practices" and where there is room for improvement.

In [106]:
# this code follow good coding practices by using full sentences to describe 
#the inputs and the outputs of a function. However, there is room for improvement by clarifying which
#variables are constants and which are not by making constants have their variables fully upper-case.

# 3 Your Turn!
Now its your turn to make a module! Choose a topic from a class (could be physics, computer science, nuclear engineering, biology, astronomy, math, or an topic that interests you!) and build a module around it! Look at my module called `example.py` and base your structure around it. Your module NEEDS to include the following.

Overall:
1) Your module needs to use at least one NumPy function: https://numpy.org/devdocs/reference/routines.math.html
2) Your module needs to contain a multi-dimensional array: https://numpy.org/devdocs/reference/arrays.ndarray.html 
3) Your module needs **at least** three functions that follow good coding practices.
4) Inside your function, include comments. Don't forget to describe what the function is doing and what the inputs and outputs are.
5) Your module needs either a `for` loop or `while` loop.
6) Your module needs an `if`, `elif`, and `else` statement.
7) Your module needs at least two assignment variables (`+=`, `*=`, etc).
8) Creativity. *If it looks like you plugged this whole thing into ChatGPT, I will take off points. You can use ChatGPT to help you code, but you can't use it to just do your homework for you. That's no fun :(*

In 2-3 sentences, describe the topic of your module and its capabilities. 

In [108]:
# My module is on photon wavelengths, energies, and hydrogen absorption lines. It can take a 2d array
# of photon wavelengths in any number of photon packages. It can tell which photon packages will
# lead to ionization, Hα absorption lines, or no reaction. It can only take in wavelengths in nanometers.
# The hydrogen status function returns an approximation with error bound +-0.02 eV.

In 2-3 sentences, answer the following. What was the most challenging part of building this module? What did you learn in the process that you can apply to future coding assignments?

In [110]:
# The most challenging part of building this module was visualing how the 2D arrays were being 
# accessed in various parts of my code. I learned that slowing down and really taking the time to
# visualize what was going on, and also running parts of the function to make sure they work, can
# save a lot of time.

Once your module is complete, import it here.

In [112]:
import photon_energies as pe

Call each of your functions in the cell below. Make sure to show the outputs! 

In [114]:
photon_wavelength = np.array([[656.4,486.2,410,],[434,321,50],[456,900,0.01]])

energies = pe.energy_of_photons(photon_wavelength)
frequencies = pe.wavelength_to_frequency(photon_wavelength)
status = pe.hydrogen_status(photon_wavelength)

print(energies)
print(frequencies)

print(status[0])
print(status[1])
print(status[2])

[[1.88887e+00 2.55009e+00 3.02403e+00]
 [2.85680e+00 3.86247e+00 2.47970e+01]
 [2.71897e+00 1.37761e+00 1.23985e+05]]
[[4.56722e+14 6.16603e+14 7.31201e+14]
 [6.90766e+14 9.33933e+14 5.99585e+15]
 [6.57440e+14 3.33103e+14 2.99792e+19]]
['0 ionized. 1 alpha-lines produced. 1 beta-lines produced. 0 gamma-lines produced. 1 delta-lines produced. 0 remaining photons.']
['1 ionized. 0 alpha-lines produced. 0 beta-lines produced. 1 gamma-lines produced. 0 delta-lines produced. 1 remaining photons.']
['1 ionized. 0 alpha-lines produced. 0 beta-lines produced. 0 gamma-lines produced. 0 delta-lines produced. 2 remaining photons.']


# 4 Proper Submission
To recieve full credit for this assignment make sure you do the following:

1) Copy this homework assignment from the `ulab_2024` repository into **YOUR** local `homework7` branch. It will contain this notebook and an additional file called `example.py`. 
   
2) Follow the tasks. Make sure to run all the cells so that **all** output is visible. You will get points taken off if your ouputs are not shown!

3) Add/commit/push this notebook and **ANY** modules (so you should have `example.py` and your module) used in this homework assignment to your remote `homework7` branch. Make sure to have NOTHING else in your branch (i.e. no previous homeworks or lecture notes).

4) Do the following:
- Take a screenshot of moving **into or out** of your `homework7` brach, call it `hw7_branch`.
- Take a screenshot of calling `ls` in your `homework7` branch, it should only contain items relevent to homework 7, call it `hw7_ls`.
- Take a screenshot of adding this assignment to your local `homework7` branch, call it `hw7_add`.
- Take a screenshot of committing this assignment to your local `homework7` branch, call it `hw7_commit`.
- Take a screenshot of pushing this assignment to your remote `homework7` branch, call it `hw7_push`. 

6) Include these screenshots in your `homework7` branch. Upload your `homework7` branch to Gradescope!